name: Deploy App on 

on:
  push:
    branches: 
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build
      run: |
        cd client  # Navigue dans le dossier 'client'
        npm install  # Installe les dépendances
        npm run build  # Exécute la commande de build

    - name: Sync files
      uses: 
