name: Deploy App on CPanel

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  if: github.event.pull_request.merged == true
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies and build
      run: |
        cd client
        npm install
        npm run build

    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.4
    #   with:
    #     server: ${{ secrets.GIT_CPANEL_PWD }}
    #     username: ${{ secrets.GIT_CPANEL_USER }}
    #     password: ${{ secrets.GIT_CPANEL_PWD }}
    #     local-dir: ./client/build/
